### ISSUE TITLE
Make a game title/"Main menu" screen

### ISSUE THREAD

**Issue by yashdeep97** [cs415-project-deadmetal/unreal-project#15]
The title screen for the game should appear on starting the game as well as when the player dies. 
It should contain at least the following items:
1. Title
2. "New Game" Button
3. "Continue" Button
-  To implement this we might need to store the checkpoint information to persistent memory - possibly a major change
5. "Quit" Button

Additionally a "Quit to Main Menu" button is required on the restart widget which will redirect to this screen.

Alternatively we could combine the title and restart screens into one.

**Comment by viapix** [comment]
Significant progress on this has been made on 3fb2191. Todo: Make death and win menus have a main-menu option. Checkpoint information is a variable within the `BP_PlayerCharacter` so it is already persistent as long as the whole character is not outright destroyed (which only happens when starting a new game).
